spring:
  datasource:
    url: jdbc:postgresql://abul.db.elephantsql.com:5432/wqvjbqne
    username: wqvjbqne
    password: z_Lw-LBjOgQzqSPwb5xrYgokViSQ4yZa
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never
  config:
    activate:
      on-profile: prod