
### create the customer №1
POST http://localhost:9000/customers
Content-Type: application/json

{
    "name": "Ihor Dzheva",
    "email": "dzheva@test.com",
    "age": 30
}

### create the customer №3
POST http://localhost:9000/customers
Content-Type: application/json

{
  "name": "Vasyl Stus",
  "password": "Vasyl2222",
  "phoneNumber": "+380631074477",
  "email": "stus@test.com",
  "role": "USER",
  "age": 47
}

### get the customer-1
GET http://localhost:9000/customers/1

### get the customer-2
GET http://localhost:9000/customers/2

### get the customer-3
GET http://localhost:9000/customers/3

### get all customers
GET http://localhost:9000/customers/all
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzExMzcwNzM5LCJleHAiOjE3MTE0NTcxMzl9.MVW7-rQeEr2RGyZTXqqZ2Lr9xkmRxYm3qGmTzIMdkORkDmmGlxnR0LKUbK7AyLXDgm30KVLO3I64RK5MnJyA1A

### delete an customer
DELETE http://localhost:9000/customers/1

### update an customer
PUT http://localhost:9000/customers
Content-Type: application/json

{
  "id": 3,
  "name": "Ihor Dzheva",
  "email": "dzheva@test.com",
  "age": 25
}

### create an account for the customer-1
POST http://localhost:9000/customers/1

### create an account for the customer-2
POST http://localhost:9000/customers/2

### create an account for the customer-3
POST http://localhost:9000/customers/3

### delete the account-1 from the customer-1
DELETE http://localhost:9000/customers/deleteAccount?customerId=1&accountId=1

### delete the account-2 from the customer-2
DELETE http://localhost:9000/customers/deleteAccount?customerId=2&accountId=2

### get page-all-customers(pagination)
GET http://localhost:9000/customers/page-all-customers

